# Generated by Django 2.2.10 on 2020-06-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('become_donors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomeplasmadonors',
            old_name='attach',
            new_name='documents',
        ),
    ]
